/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ASUS
 */
public class mainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainFrame.class.getName());

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        
        
        panelRounded(panelAnggrek);
        panelRounded(panelKamboja);
        panelRounded(panelMatahari);
        panelRounded(panelMawar);
        panelRounded(panelMelati);
        panelRounded(panelSakura);
        
        
        
        tambahMouseListener(panelAnggrek);
        tambahMouseListener(panelKamboja);
        tambahMouseListener(panelMatahari);
        tambahMouseListener(panelMawar);
        tambahMouseListener(panelMelati);
        tambahMouseListener(panelSakura);

    }
    
    public void panelRounded(JPanel panel){
        
        panel.setBorder(new FlatLineBorder(
                new Insets(0, 0, 0, 0), new Color(147, 147, 147), 0, 25
        ));
    }
    
    
    private void tambahMouseListener(JPanel panel){
        
        Color warnaNormal = new Color(255, 255, 255);
        Color warnaHover = new Color(230, 244, 253);
        
        panel.setOpaque(true);
        panel.setBackground(warnaNormal);
        panel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        panel.addMouseListener(new MouseAdapter(){
            
            @Override
            public void mouseEntered(MouseEvent e){
                panel.setBackground(warnaHover);
            }
            
            @Override
            public void mouseExited(MouseEvent e){
                panel.setBackground(warnaNormal);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelAnggrek = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelKamboja = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelMatahari = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelMawar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelMelati = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelSakura = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 236, 239));

        jPanel2.setBackground(new java.awt.Color(234, 236, 239));
        jPanel2.setMinimumSize(new java.awt.Dimension(579, 683));
        jPanel2.setPreferredSize(new java.awt.Dimension(579, 683));
        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 24, 24));

        panelAnggrek.setBackground(new java.awt.Color(255, 255, 255));
        panelAnggrek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAnggrekMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel2.setText("Anggrek");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/anggrek.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow kanan.png"))); // NOI18N

        javax.swing.GroupLayout panelAnggrekLayout = new javax.swing.GroupLayout(panelAnggrek);
        panelAnggrek.setLayout(panelAnggrekLayout);
        panelAnggrekLayout.setHorizontalGroup(
            panelAnggrekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnggrekLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnggrekLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        panelAnggrekLayout.setVerticalGroup(
            panelAnggrekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnggrekLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAnggrekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnggrekLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnggrekLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32))))
        );

        jPanel2.add(panelAnggrek);

        panelKamboja.setBackground(new java.awt.Color(255, 255, 255));
        panelKamboja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelKambojaMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel5.setText("Kamboja");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/kamboja.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow kanan.png"))); // NOI18N

        javax.swing.GroupLayout panelKambojaLayout = new javax.swing.GroupLayout(panelKamboja);
        panelKamboja.setLayout(panelKambojaLayout);
        panelKambojaLayout.setHorizontalGroup(
            panelKambojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKambojaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKambojaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        panelKambojaLayout.setVerticalGroup(
            panelKambojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKambojaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKambojaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        jPanel2.add(panelKamboja);

        panelMatahari.setBackground(new java.awt.Color(255, 255, 255));
        panelMatahari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMatahariMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel8.setText("Matahari");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/matahari.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow kanan.png"))); // NOI18N

        javax.swing.GroupLayout panelMatahariLayout = new javax.swing.GroupLayout(panelMatahari);
        panelMatahari.setLayout(panelMatahariLayout);
        panelMatahariLayout.setHorizontalGroup(
            panelMatahariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatahariLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatahariLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9))
        );
        panelMatahariLayout.setVerticalGroup(
            panelMatahariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatahariLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatahariLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        jPanel2.add(panelMatahari);

        panelMawar.setBackground(new java.awt.Color(255, 255, 255));
        panelMawar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMawarMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel11.setText("Mawar");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Mawar.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow kanan.png"))); // NOI18N

        javax.swing.GroupLayout panelMawarLayout = new javax.swing.GroupLayout(panelMawar);
        panelMawar.setLayout(panelMawarLayout);
        panelMawarLayout.setHorizontalGroup(
            panelMawarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMawarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMawarLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        panelMawarLayout.setVerticalGroup(
            panelMawarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMawarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMawarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMawarLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMawarLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(32, 32, 32))))
        );

        jPanel2.add(panelMawar);

        panelMelati.setBackground(new java.awt.Color(255, 255, 255));
        panelMelati.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMelatiMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel14.setText("Melati");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Melati.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow kanan.png"))); // NOI18N

        javax.swing.GroupLayout panelMelatiLayout = new javax.swing.GroupLayout(panelMelati);
        panelMelati.setLayout(panelMelatiLayout);
        panelMelatiLayout.setHorizontalGroup(
            panelMelatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMelatiLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMelatiLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap())
        );
        panelMelatiLayout.setVerticalGroup(
            panelMelatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMelatiLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMelatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMelatiLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMelatiLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(32, 32, 32))))
        );

        jPanel2.add(panelMelati);

        panelSakura.setBackground(new java.awt.Color(255, 255, 255));
        panelSakura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSakuraMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel17.setText("Sakura");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sakura.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow kanan.png"))); // NOI18N

        javax.swing.GroupLayout panelSakuraLayout = new javax.swing.GroupLayout(panelSakura);
        panelSakura.setLayout(panelSakuraLayout);
        panelSakuraLayout.setHorizontalGroup(
            panelSakuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSakuraLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSakuraLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        panelSakuraLayout.setVerticalGroup(
            panelSakuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSakuraLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSakuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSakuraLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSakuraLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(51, 51, 51))))
        );

        jPanel2.add(panelSakura);

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Direktori Bunga");

        jLabel20.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Koleksi bunga pilihan yang melambangkan keindahan, ketulusan,");

        jLabel21.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("semangat, dan awal yang baru.");

        jLabel22.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel22.setText("Kelompok 2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelAnggrekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnggrekMouseClicked
        // TODO add your handling code here:
        new frameAnggrek().setVisible(true);
        
        dispose();
    }//GEN-LAST:event_panelAnggrekMouseClicked

    private void panelKambojaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKambojaMouseClicked
        // TODO add your handling code here:
        new frameKamboja().setVisible(true);
        
        dispose();
    }//GEN-LAST:event_panelKambojaMouseClicked

    private void panelMatahariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMatahariMouseClicked
        // TODO add your handling code here:
        new frameMatahari().setVisible(true);
        
        dispose();
    }//GEN-LAST:event_panelMatahariMouseClicked

    private void panelMawarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMawarMouseClicked
        // TODO add your handling code here:
        new frameMawar().setVisible(true);
        
        dispose();
    }//GEN-LAST:event_panelMawarMouseClicked

    private void panelMelatiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMelatiMouseClicked
        // TODO add your handling code here:
        new frameMelati().setVisible(true);
        
        dispose();
    }//GEN-LAST:event_panelMelatiMouseClicked

    private void panelSakuraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSakuraMouseClicked
        // TODO add your handling code here:
        new frameSakura().setVisible(true);
        
        dispose();
    }//GEN-LAST:event_panelSakuraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.put("Button.arc", 25);
            UIManager.put("Button.borderwidht", 0);
            UIManager.put("TextComponent.arc", 10);
            UIManager.put("Component.borderwidht", 0);
            UIManager.put("Component.focusWidth", 0);
            UIManager.put("Component.innerFocuswidht", 0);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelAnggrek;
    private javax.swing.JPanel panelKamboja;
    private javax.swing.JPanel panelMatahari;
    private javax.swing.JPanel panelMawar;
    private javax.swing.JPanel panelMelati;
    private javax.swing.JPanel panelSakura;
    // End of variables declaration//GEN-END:variables
}
